server:
    interface: 0.0.0.0
    interface: ::0
#    interface: 2001:e68:545c:d70:20c:29ff:fed0:b64f
#    access-control: 2001:e68:545c::/48 allow
    access-control: 192.168.88.0/24 allow
    access-control: ::/0 allow
    module-config: "respip dns64 validator cachedb iterator"
#    dns64-prefix: 64:ff9b::/96
    logfile: "/var/log/unbound/unbound.log"
    verbosity: 1
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
         num-threads: 4
         port: 53
         outgoing-range: 166
         so-rcvbuf: 2m
         so-sndbuf: 2m
         so-reuseport: yes
         msg-cache-size: 128m
         msg-cache-slabs: 4
         num-queries-per-thread: 83
         rrset-cache-size: 256m
         rrset-cache-slabs: 4
	 prefetch: yes
         cache-min-ttl: 0
         infra-cache-slabs: 4
         do-ip4: yes
         do-ip6: yes
        username: "unbound"
         directory: "/etc/unbound"
         log-time-ascii: yes
          root-hints: /var/lib/unbound/root.hints
          harden-dnssec-stripped: yes
         prefetch-key: yes
         serve-expired: yes
         serve-expired-ttl: 0
         key-cache-slabs: 4
         ratelimit: 0
	 max-global-quota: 300
rpz:
         name: "unbound-adblock"
         zonefile: "/etc/unbound/adblock.rpz"
         rpz-log: yes
         rpz-log-name: "unbound-adblock"
remote-control:
         control-enable: yes
          control-interface: 127.0.0.1
         control-port: 8953
         server-key-file: "/etc/unbound/unbound_server.key"
         server-cert-file: "/etc/unbound/unbound_server.pem"
         control-key-file: "/etc/unbound/unbound_control.key"
         control-cert-file: "/etc/unbound/unbound_control.pem"
 cachedb:
     backend: "redis"
     redis-server-host: 127.0.0.1
     redis-server-port: 6379
     redis-timeout: 100
     redis-expire-records: no
forward-zone:
    name: "steamcdn-a.akamaihd.net"
    forward-addr: 8.8.4.4
forward-zone:
    name: "steamstatic.com"
    forward-addr: 8.8.4.4
forward-zone:
    name: "media.steampowered.com"
    forward-addr: 8.8.4.4
forward-zone:
    name: "steamserver.net"
    forward-addr: 8.8.4.4
forward-zone:
    name: "steampowered.com"
    forward-addr: 8.8.4.4
forward-zone:
    name: "steamcommunity.com"
    forward-addr: 8.8.4.4
forward-zone:
    name: "steamcontent.com"
    forward-addr: 8.8.4.4
forward-zone:
    name: "steamusercontent.com"
    forward-addr: 8.8.4.4
forward-zone:
    name: "video.fastly.steamstatic.com"
    forward-addr: 8.8.4.4

